#! /bin/sh

# Make sure bspwm removes all its rules for a clean restart
bspc rule -r "*"

# due to pulseaudio being pulseaudio, this is required
# maybe something to do with this: https://github.com/baskerville/bspwm/issues/165
# pulseaudio --kill
# pulseaudio --start

# --- Autostart --- #
xrdb ~/.Xresources &

# Setup workspaces
bspc monitor -d 1 2 3 4 5

# Set wallpaper
feh --bg-scale /home/donal/pictures/wallpapers/1.png 

# Start picom if dead
pgrep -x picom > /dev/null || picom --experimental-backends --backend glx -b &

# Start sxhkd if dead
pgrep -x sxhkd > /dev/null || sxhkd &

# Start polybar
/home/donal/sysscripts/launch_polybar.sh

# --- Monitors & Desktops --- #
/home/donal/sysscripts/bspwm_monitors_and_desktops.sh

# --- Workspaces --- #
bspc config automatic_scheme alternate
bspc config initial_polarity second_child

# --- Windows --- #
# Colors
bspc config normal_border_color "#151515"
bspc config focused_border_color "#E6B673"
bspc config active_border_color "#252e77"
bspc config urgent_border_color "#e06c75"

bspc config pointer_modifier super
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action_3 resize_corner

bspc config click_to_focus none
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

# Gaps
bspc config border_width         2
bspc config window_gap          10

# Modes
bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false
