require("keymaps")
require("plugins")
require("options")

-- plugin configs
require("plugins_config.nightfox")
require("plugins_config.feline")
require("plugins_config.telescope")
require("plugins_config.treesitter")
require("plugins_config.lazygit")
require("plugins_config.lsp_config")
require("plugins_config.completions")
require("plugins_config.null-ls")
require("plugins_config.lsp_saga")
require("plugins_config.gitsigns")
require("plugins_config.copilot")
require("plugins_config.copilot_cmp")
