require("plugins_config.nightfox")
require("plugins_config.lualine")
require("plugins_config.nvim-tree")
require("plugins_config.telescope")
require("plugins_config.treesitter")
require("plugins_config.lazygit")
require("plugins_config.lsp_config")
require("plugins_config.completions")
